### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by Misio12320** [Pokechu22/WorldDownloader#102]
Hello. Can @Pokechu22 add feature like a seed steal some like this or just get the seed without permission on server?

**Comment by Pokechu22** [comment]
Unfortunately, no, getting the seed on a server without permission to use `/seed` has not been possible since the seed field was removed from the 0x01 login request packet in [1.2.2](https://wiki.vg/index.php?title=Protocol&type=revision&diff=735&oldid=718) (6.5 years ago).  Other methods of getting this would be outside of the scope of the mod.  Sorry.

**Comment by Misio12320** [comment]
Thanks for understand well... I asked the owner of server to give me the download world and he said later so... good... Edit: Close, if you have something to say, say if not lock em...

**Comment by Pokechu22** [comment]
That's great; in general, the social solution (asking someone e.g. the server owner if they can give you what you need) is easier than the technical solution.  Closing as you've said.
