### ISSUE TITLE
Download Entire World

### ISSUE THREAD

**Issue by NPCtom** [Pokechu22/WorldDownloader#109]
Is there any possible way to add a feature to download the entire world. Maybe like a freecam that moves really fast and downloads chunks?

I would be more than happy to donate if you add this feature :)

**Comment by Pokechu22** [comment]
It's not technically feasible, unfortunately.  You have to load a chunk to see it, and that means being in the area (freecam, by definition, doesn't move the player and wouldn't load chunks).

Do remember that you can save part of the world and then start downloading again later to merge parts together (this happens automatically).  For a while, I've wanted to add some kind of overlay or screen that indicates what areas have been saved before and what areas haven't to simplify things like this but haven't gotten around it.  You can render the map with an external program such as [overviewer](http://overviewer.org/) though.

n.b. I do not accept money with regards to this mod for personal reasons.

**Comment by NPCtom** [comment]
The screen that shows the area you have downloaded sounds cool as! Maybe when the player presses a dedicated key e.g M a map will show up showing the chunks you have downloaded.

Do you have any idea on when this could be added?

**Comment by Pokechu22** [comment]
I don't know when I'll get around to adding it; it's something I've had on my backlog for a while.  It won't be in the next release (my current plans are to fix several map (item) related issues and improve the custom backup function, and _hopefully_ also get the buildscript issues fixed which is more technical).  It might be in the release after that, but I also want to improve the multiworld UI first since that confused basically everyone... there's a lot to do, for sure.

**Comment by Eyremba** [comment]
> The screen that shows the area you have downloaded sounds cool as! Maybe when the player presses a dedicated key e.g M a map will show up showing the chunks you have downloaded.

It would be nice if it would also highlight a chest if you have not opened them during the saving process (or vice versa) so that you immediately know which chests you have saved with their content and which not.
