### ISSUE TITLE
Gamerules Change

### ISSUE THREAD

**Issue by NPCtom** [Pokechu22/WorldDownloader#111]
If I execute the command /gamerule doFireTick false and I then continue downloading a world the gamerule then resets to true. Is there a way to always have that gamerule variable set to false to prevent fire burning wood etc.

**Comment by Pokechu22** [comment]
Yes, set it in the gamerules GUI instead; WDL uses the info in that GUI to decide what the values of gamerules should be and _currently_ uses the default values if they're not specified there.

It should be possible for me to import existing values instead of overwriting them with the defaults (so that changing it with `/gamerule` would also work), though I'm not 100% sure if I can do it in a way that's clear on the UI.  I'll look into it.

**Comment by NPCtom** [comment]
OK thanks Pokechu :) Issue Closed.
