### ISSUE TITLE
Can this be compiled for 1.14 as of yet? If so, how?

### ISSUE THREAD

**Issue by BlueCyro** [Pokechu22/WorldDownloader#119]

**Comment by Pokechu22** [comment]
Not yet.  I'm still working on resolving the buildscript issues needed to even start on 1.14 support.  I don't have any ETA yet, sorry.

**Comment by BlueCyro** [comment]
@Pokechu22 Ahh okay then, in the meantime, are you aware of any alternatives for doing this on 1.14, or do you suppose I'm SOL in that department since the release is still so early?

**Comment by Pokechu22** [comment]
Currently SOL, sorry.  Hopefully I can get something out this week but I can't say for sure.

**Comment by BlueCyro** [comment]
@Pokechu22 No worries, at least it seems to be a (relatively) easy mod to update in comparison to the other ones I've seen.

**Comment by Rayska** [comment]
Hi! Sorry if I'm missing something here, are there any news on this? I there a 1.14 compatible version yet?

**Comment by Pokechu22** [comment]
Not yet.  I'm *almost* there for 1.14.0 (I got something to finally compile after copy-pasting all the code in a super messy way, but I'm pretty sure things are still broken), but it's not quite done yet.  I'll probably have some initial (probably fairly buggy) build out in a few days, but I'm not sure of that.

**Comment by Rayska** [comment]
Alright, thank you for your swift response!

**Comment by Pokechu22** [comment]
Status update: I've got things that successfully compile for 1.14.0, 1.14.1, and 1.14.2.  Currently, unit tests are not passing (I've commented out several and others are marked as skipped), with the current status being 242 runs (31 skipped), Errors: 18, Failures: 0.  The main thing that's broken is inventory display names, which I think is minor enough that I'm not going to delay over it (all relevant tests are skipped).  I _have not_ actually gotten to the point where I can test ingame.  Things might work fine there, or they might be broken.

I currently have 88 new commits locally (things are still rather broken, so I've been avoiding pushing since I want `master` to compile cleanly).  The build system is still rather broken, but after manually handling patching things seem to work consistently (this only apply to 1.14.x; 1.13.x is still completely broken in terms of others building and 1.12.x and earlier are fine).  I probably will just stick with the manual build patch process for now, since it's better than nothing.

I hope to get some initial build out over this weekend.

**Comment by Pokechu22** [comment]
Current status: the game launches, but crashes on starting download and most of the GUIs are messed up:

![This is fine](https://user-images.githubusercontent.com/8334194/59234797-319fd800-8ba3-11e9-8a09-29e76adab80d.png)
![I see absolutely nothing wrong with tͬ̍̎̈̆̏ͯ͑̈͗́̂̅́͘͟͡҉̟̪̙͖̭̰̯h̊ͮͫͩ͊ͭ͒̽̆̽ͧ͛ͧ̿̉͗́͐͘͞͏̞̞̙̮̭͖̘̫͈̗̫̮̫̼i̴̶̧̱͕̭̣͖̹̲̮̠̬̊̾̄̉ͅs̸̡̘̩̟̳̣͓̘̝͍̜̲̫̦̳̺͑͋̌̍ͭ̀ͫ̍ͩ̉͗͌͆̾̎͒̽̏ͥ͞͠͞ͅ](https://user-images.githubusercontent.com/8334194/59234798-319fd800-8ba3-11e9-9b68-f1b5ef9ce209.png)

Hopefully I'll get this fixed today or tomorrow.  The annoying thing is that I can't test in my IDE, so I have to manually build and install the mod, and then test by launching the game, and that's pretty slow.

**Comment by Pokechu22** [comment]
[Version 4.0.5.0](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.5.0) has released!  (See the latest comment on #116 for information about compiling it yourself; it's a bit complicated but should be doable (unlike 1.13, which is currently still a bit of a nightmare)).
