### ISSUE TITLE
Decompiling with MCP 9.08 Minecraft 1.7.10 results in multiple compile time errors

### ISSUE THREAD

**Issue by Bjohnson131** [Pokechu22/WorldDownloader#120]
Hello.
I'm trying to use this for development in minecraft 1.7.10.

I'm getting a plethora of errors while setting up my workspace, you can see a full list here: (https://pastebin.com/dXdft7kz) apologies if this is an issue with MCP. many of the errors are missing fields, eg: 
Description	Resource	Path	Location	Type
The method getClientBrand() is undefined for the type EntityClientPlayerMP	WorldClient.java	/Client/src/net/minecraft/client/multiplayer	line 376	Java Problem

Client type: eclipse
OS: Win10
MCP: 9.08

How to reproduce:
1) download MCP, 1.7.10, the server jar, and the sources for this mod.
2) pass the minecraft JAR files to MCP, and decompile.
3) open eclipse up with the eclipse workspace folder given to you by MCP
4) update the mojang netty library and auth library in the guild path because MCP sets you up with some versions that are too early.
5) use the provided sources from the repo, place /wdl/ into the /src/minecraft/ folder in the mcp base folder. Also place /mcp/src/ from the repo int othe /src/ folder that MCP made.
6) load eclipse with the mentioned workspace. Voila. Error produced.

Edit: I should mention I'm pulling code from here:https://github.com/Pokechu22/WorldDownloader/tree/1.7.10c-beta2

**Comment by Pokechu22** [comment]
I think you probably have the wrong mappings.  E.g. `isCallingFromMinecraftThread` used to not have a name, so it would display as `func_152345_ab`, until 2014-08-19 when it was changed to actually have a name.  I _think_ that the correct mapping csv files are located somewhere in the project, but I remember it being a giant mess to swap to them but not overwrite other things (you need to extract MCP, but keep _these_ files as the ones included in the repo instead of the older ones that MCP used).

1.7.10, being nearly 5 years old, is out of the scope of what I normally maintain nowadays.  So I don't remember exactly was needed.  If you need more help, I'll try to dig up more information about how I had things set up, though.

**Comment by Bjohnson131** [comment]
Good hint. The proper solution is to clean the MCP folder, copy the conf/*.csv files to the corresponding folder in the MCP workspace, then Decompile, and re-copy the sources.

Thank you so much for the help!

**Comment by Pokechu22** [comment]
That sounds about right.  Glad to help!
