### ISSUE TITLE
Nether not downloading

### ISSUE THREAD

**Issue by smikkelvriend** [Pokechu22/WorldDownloader#125]
My nether is not downloading, when I go through a portal in the saved chunks it says it has downloaded it, but when I go into the world and go through a portal I create a new portal. When that portal is created all the chunks around me are new, so it's not saving or something.
I also tried stopping the download when in the nether, but then I do spawn on those coordinates, but it's all new generated chunks, so I fall in lava.

**Comment by Pokechu22** [comment]
Is this 1.14, or an earlier version?  My guess at what's happening is that I'm using the wrong folder when saving other dimensions, so it's saving nether chunks in an overworld folder.  You could check by trying to teleport to the nether coordinates while in the (probably otherwise empty) overworld of the separate nether world.

**Comment by Pokechu22** [comment]
Can you check if this still exists in [version 4.0.5.1](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.5.1)?  I completely forgot about this bug, and it's rather late for me so I don't have time to test tonight.

**Comment by Pokechu22** [comment]
I got around to testing this; it still exists.

The problem is that it saves the chunks for the nether into <code>world/DIM-1/r.<var>x</var>.<var>z</var>.mca</code>, but it should save them into <code>world/DIM-1/<ins>region</ins>/r.<var>x</var>.<var>z</var>.mca</code>.  It should be easy to fix.  In the mean time, the saved chunks still exist and should be manually movable.

**Comment by Pokechu22** [comment]
Fixed in [version 4.0.5.2](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.5.2).
