### ISSUE TITLE
will not let me enable multiworld support

### ISSUE THREAD

**Issue by Onefunction** [Pokechu22/WorldDownloader#128]
I press enable in multiworld support then press done and it just redisables it and moves my cursor to the center of the screen. 1.14.3

**Comment by Pokechu22** [comment]
Confirmed.  I'm not sure why this is happening.  Unfortunately I don't think I'll have time to look into it for a few days.  You might be able to work around the issue by copying a group of worlds where multiworld support was already enabled before, though.  Otherwise, just work with multiworld support disabled for now.

**Comment by Onefunction** [comment]
Thank you for your response. It worked with the part i was trying to copy anyways, thank you

**Comment by Pokechu22** [comment]
Apparently this was also broken in 4.0.5.0.  I'm surprised nobody noticed/reported it before...

**Comment by Pokechu22** [comment]
Cause: I made this mistake in 65957cd2b659fd8cf96be0576c36fc06f23aa344, and _somehow_ failed to notice it the 6 months that followed.  (Confirmed by running the 1.12.2 litemod from the code from [then](https://github.com/Pokechu22/WorldDownloader/archive/65957cd2b659fd8cf96be0576c36fc06f23aa344.zip) and [one commit earlier](https://github.com/Pokechu22/WorldDownloader/archive/83eb8351561e80ffaa345e9d0f94f940e54eaddf.zip)).  I moved the `isMultiworld` check to be after the `propsFound` check, which broke things completely as the `isMultiworld` check is used to set `propsFound` if multiworld is enabled.  Thus, it continuously hits the `propsFound` check, which asks if multiworld should be enabled, instead of progressing to the enter a name screen.

This code is messy, but it shouldn't be too hard to fix.

**Comment by Onefunction** [comment]
Haha 6 months and no one mentioned it?

**Comment by Pokechu22** [comment]
To be clear, it was 6 months since I made that change, but it only ended up in release 4.0.5.0 back on June 10th, so it's only been "live" for a month.  Still, given how obvious it is, it's something I'd have expected to have been noticed sooner...

**Comment by Pokechu22** [comment]
Fixed in [version 4.0.5.2](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.5.2).
