### ISSUE TITLE
Support for 1.14.4?

### ISSUE THREAD

**Issue by NaNraptor** [Pokechu22/WorldDownloader#130]
I am not sure how to build this myself for 1.14.4, even though I tried (not enough docs + not enough experience), any help or an outright release will be very welcome

**Comment by uyjulian** [comment]
1.14.4 is not supported yet.

**Comment by Pokechu22** [comment]
Indeed, it's not supported yet.  The latest version there is code for is 1.14.3; to add 1.14.4 won't be too hard but it's a bit of an involved process (copying the 1.14.3-specific code folder to 1.14.4, adding 1.14.4 to the list in the root settings.gradle and build.gradle files, changing the version in the new 1.14.4 build.gradle file (and because of jank stuff, also manually updating the libraries list... and all of this depends on the forge team releasing updated MCP data (which I think they have, but I haven't fully checked yet)), and fixing whatever new compile errors might occur).  I probably should document how to do it better at some point, but first I need to (of course) improve the build system...

I'll probably have a 1.14.4 build sometime this week.

**Comment by NaNraptor** [comment]
Thanks for the quick replies, once more docs have been released I would be happy see if I can contribute in any way too, I have some fair experience with java

**Comment by Slx-hub** [comment]
I gave it a try, and this is how far i've got:

A problem occurred evaluating project ':1.09.0'.
> java.lang.NoClassDefFoundError: net/minecraftforge/gradle/user/UserVanillaBasePlugin

Begradle has been installed, at least somewhat successful.
Before that, i got an error saying Begradle doesn't support java 9, so something definitely worked..

**Comment by Pokechu22** [comment]
I've released [version 4.0.5.3](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.5.3), which includes 1.14.4 support.  I also 'documented' the process for it with slightly more descriptive commits referencing this issue (though one change to them: I implemented `setupDecompWorkspace` for ForgeGradle 3 afterwards, so `regenEclipse` is not necessary for the most part anymore).  It's not the best documentation possible but hopefully it should at least serve as notes for something better.

SlaxXxX: That error is weird, and it looks like ForgeGradle itself failed to download.  Did you get a warning above that regarding certificates or something?  If so, make sure you've got the most recent version of the java 8 JDK (which you can get from [AdoptOpenJDK](https://adoptopenjdk.net/)).

**Comment by NaNraptor** [comment]
Thanks for your time and effort I think the original issue here was resolved so I will close
