### ISSUE TITLE
Crash with Optifine 1.14.2

### ISSUE THREAD

**Issue by mben42** [Pokechu22/WorldDownloader#135]
Hi,

I got a crash at server connection when using both WDL and Optifine 1.14.4 HD U F2 as jar mods with MultiMC. No crash occurs when using WDL only.

Steps to reproduce: use MultiMC, install OptiFine 1.14.4 HD U F2, install WDL 4.0.5.3, start Minecraft, connect to a server.

Crash report: https://pastebin.com/pDK4tauf

Regards,

**Comment by Pokechu22** [comment]
Due to the nature of base edits/jar mods, they tend to be incompatible with each other.  You'll just need to not have optifine installed for the moment.  When I get around to porting to forge or something else (which takes a while due to build system issues) then it might be possible to have compatibility though.

**Comment by mben42** [comment]
Thanks for your answer, actually I just need the WDL to save a world sometimes, I can disable Optifine at these times.
