### ISSUE TITLE
Chests contents not being saved v4.0.5.3

### ISSUE THREAD

**Issue by beans42** [Pokechu22/WorldDownloader#136]
Title. It doesn't save the contents and doesn't say anything about it in chat. On minecraft 1.14.3. v4.0.5.1 saves chest contents. Still a great mod though!

**Comment by Pokechu22** [comment]
I'll need to test this in the morning, but this seems odd since I don't think I made any changes that would affect saving chests between 4.0.5.1 and 4.0.5.3 and the unit tests should have caught something like that (though it's possible that the issue is an area not covered by them).  Is 4.0.5.2 affected?

**Comment by Pokechu22** [comment]
I can't reproduce.  Chests seem to save fine for me in 4.0.5.3, with both Minecraft 1.14.3 and Minecraft 1.14.4.

Make sure that both of the gui closed messages are enabled in message settings; maybe you have them off and that's why you're not seeing anything in chat?
