### ISSUE TITLE
Tests Failed while building

### ISSUE THREAD

**Issue by AlexLander123** [Pokechu22/WorldDownloader#138]
While running `gradlew setupDecompWorkspace build`, everything works fine till the tests for 1.14.1. Thus, I tried building just 1.14.1 using `gradlew 1.14.1:build` and some of the test still failed. 

These are the tests that failed:
![image](https://user-images.githubusercontent.com/13492360/62876594-de3f3700-bd57-11e9-9c88-5ae9efc64a7a.png)

For the SanityCheckTest, most of the errors were regarding to missing base changes.
Example:
> java.lang.Exception: CrashReport is missing base changes!

For WDLHooksTest, most errors were:
> Wanted but not invoked:

The rest are translation key should be present errors.
Example:
> java.lang.AssertionError: Translation key should be present: wdl.messages.category.core_recommended

**Comment by Pokechu22** [comment]
Are you using the latest build?  (Since it's failing on 1.14.1, I assume so and that this isn't one of the natives issues I fixed in 68a1e5119d0ad8a5e9d8019704beeb2edeb56686 since that only affects 1.14.2 and later).

Try running `gradlew :1.14.1:applyBasePatches :1.14.1:processResources` and then running `:1.14.1:build`.  That _shouldn't_ be necessary since `build` depends on both of those, but that should generate the base patches and then also create the new-format language file.  (All of the failed tests are either due to base changes being missing (kinda important to use the mod) or messages not being present (less important, but a messy user experience and not something you'd want in production).)

**Comment by AlexLander123** [comment]
After running `gradlew :1.14.1:applyBasePatches :1.14.1:processResources` I was able to build successfully with `gradlew :1.14.1:build`. However, I have to repeat `applyBasePatches` and `processResources` for the rest of the 1.14 versions for them to build successfully.

**Comment by Pokechu22** [comment]
Sorry for not responding, but I remembered the issue that causes this: in 1.14.x, I don't have `processBasePatches` running when building (unlike 1.13.x), due to the issues with 1.14.0.  The base patches not being applied causes the same missing assets effect (and breaks a bunch of other things).  

I've fixed it so that it automatically happens in versions other than 1.14.0; 1.14.0 has its mess of manual steps to which manually running `applyBasePatches` can be added.
