### ISSUE TITLE
Cant Generate New Chunks

### ISSUE THREAD

**Issue by sopheset111** [Pokechu22/WorldDownloader#145]
After downloading a map that I want to save from a server I am unable to generate new chunks other then nether and the end from what I saved.

**Comment by sopheset111** [comment]
Update: after looking through level.dat, (I had to manual input the world seed) it listed the generator option as Biome: Minecraft.the_void which will explain it. Unsure as to how or why it got saved like this.

**Comment by Pokechu22** [comment]
WDL defaults to not generating anything since it doesn't know the world seed and attempting to generate terrain without it will produce a mess of mismatched chunks.  You can configure the world generator in the generator options menu, including filling in the seed there and setting the terrain generator to use.  Running `/seed` (if you have permission) while downloading will also fill in the seed and set the terrain generator, if you don't want to mess with the GUI.

(FYI, your issue is different from #143, which is a mod-related issue; the generation settings might explain why @Aequipondium got void when the game attempted to generate chunks, but not why they were spawning in a dimension that did not have downloaded chunks).

**Comment by sopheset111** [comment]
Ah, I managed to fix it by deleting the void sting and renaming the other biome generator varable to default from flat.

**Comment by Pokechu22** [comment]
That should work too, though manual edits to level.dat will probably be clobbered if you download the world again.

**Comment by sopheset111** [comment]
at least now I know what the issue was and how to fix it for next time.
