### ISSUE TITLE
More Superflat Presets

### ISSUE THREAD

**Issue by afanofjapan** [Pokechu22/WorldDownloader#15]

**Comment by Pokechu22** [comment]
Should be relatively easy to do - I've already made it possible to set the superflat preset in the configuration file (used so that the default chunk generator is a superflat generator that generates air).  

I think it might be possible to use the superflat GUI for this, but I'm not 100% sure.  I'll look into it.

**Comment by afanofjapan** [comment]
Okay thanks

**Comment by Pokechu22** [comment]
I've implemented this; I think I might also try to implement the customized world type.  (See 90e7f80)

**Comment by afanofjapan** [comment]
Yay! Thanks!

**Comment by Pokechu22** [comment]
Fixed in [1.8d](https://github.com/Pokechu22/WorldDownloader/releases/tag/1.8d-beta1), which I've just now released.  Also fixed in the related backports to 1.8.9, 1.8.8, and 1.7.10.  Enjoy!
