### ISSUE TITLE
Is World Downloander ilegal ??? World Downloander laws

### ISSUE THREAD

**Issue by ReneSamajStudioSK** [Pokechu22/WorldDownloader#157]
Hello 

**Is it illegal if I download maps to my server for my own purposes?
I read a lot of articles that say that if I use it for sale or for general trade it is illegal. I do not know where the truth please answer**

**Comment by Pokechu22** [comment]
I am not a lawyer.

My opinion is: if it's something you built yourself, you're free to use it for whatever purpose, and free to download it.  If it's something someone else built, then they own it, and it would be bad form to use it on your own server (especially without credit), but e.g. downloading it to make a render can be fine.  [Fair use](https://en.wikipedia.org/wiki/Fair_use) is a related concept.

I maintain this mod specifically to cover the case of making a backup of something you built on a server, since servers go down and in many cases, won't provide a copy of the world when they do go down (or, even if they *want* to do give a copy of the world, they can fail to do it due to running out of money; I've ran into this specific situation myself.)

**Comment by ReneSamajStudioSK** [comment]
Oke and if that put in my server and somthing change 
that cant be @copyright

**Comment by Pokechu22** [comment]
It still depends.  A small server for you and a few friends could be personal fair use, but a large server or a monetized server probably would be against copyright.

I am not able to give any definite answer (as I am not a lawyer, and I do not know copyright law for the entire world).  The best way to get a definite answer about whether or not you're allowed to use something, if you're unsure, is to talk to whoever created the map you would like to use.
