### ISSUE TITLE
Worlds downloaded with this mod can generate new terrian

### ISSUE THREAD

**Issue by ghost** [Pokechu22/WorldDownloader#160]
I downloaded a world using this mod, and when I run this world, if I leave the area that was downloaded, it just says, under the F3 menu, that I'm in a void biome, and no terrain is generated. It acts like a normal world, just non-downloaded chunks are the void biome.

**Comment by uyjulian** [comment]
That is intended behavior.

**Comment by Pokechu22** [comment]
Without the server seed, there isn't any way to properly generate new terrain.  Generating empty chunks is the best alternative (if regular chunks are generated with the wrong seed, you get massive walls and mismatched terrain); there isn't a convenient way to tell the world not to generate chunks at all.  (If you have the seed or otherwise want to enable terrain generation (e.g. superflat), you can do it under generator settings.)

**Comment by ghost** [comment]
I have the seed for the world that I downloaded, is there any way to put
that in?

**Comment by Pokechu22** [comment]
Yes; on the server, select "..." and then select generator options.  Put the seed in, and also change the world type to the type you want (instead of leave empty).  You will then need to start and stop download (the generator setting in level.dat is only updated when stopping download).  Note that the all-void chunks you generated are considered already generated by the game, so you'll want to either reload from a backup before you generated them (there should be one in .minecraft\backups), or overwrite them by downloading the correct chunks from the server.
