### ISSUE TITLE
Anti-WorldDownloader Bypass

### ISSUE THREAD

**Issue by FelixMountain** [Pokechu22/WorldDownloader#172]
Hi just wondering if the is some world downloader that will bypass anti-world downloader plugins on servers, I know servers might not want people with world downloader on it and I know that but it would still be nice like I suggest maybe making it and only giving it to people that really need it like in my example the server I play on does not allow world downloader but I need to use it to copy the main end island (this is towny and I have already claimed the land so the chunks are mine) but i can't because the anti-world downloader plugin (i need a copy of the main end island because it is currently griefed but I am designing it and make it look beautiful

**Comment by Pokechu22** [comment]
Yes, it is possible, and I help with it on a case-by-case basis (handled via Minecraft Forum PMs).  You've already sent me a PM, so I'll follow up there (and close this issue).

In general the main thing I suggest is asking the server admin first, since not letting you download your own works is a social problem, and it's better to solve it for everyone through social means than for just yourself through technical means.
