### ISSUE TITLE
Void

### ISSUE THREAD

**Issue by MinetopiaFan135794** [Pokechu22/WorldDownloader#193]
When i try to download a world of my server and i leave the server worlddownloader make the world and then when i join the singleplayer world i come in the good map but when i make a copy from the map i come on a void world and when i upload the map from the saves file on my server i come in void world and when i upload the map from backups i come in a void world

**Comment by MinetopiaFan135794** [comment]
I use 1.12.2 and liteloader

**Comment by Pokechu22** [comment]
I don't fully understand what you mean by "make a copy from the map".  If you're using the "re-create world" function, that generates a new world based on the existing world's generation settings.  But, World Downloader doesn't get those settings from the server; you have to configure them yourself in the generator overrides screen (which applies when you save the world).  By default, it generates void terrain (as otherwise, you would get terrain that doesn't match the server since the seed isn't known).

If you're actually copying the world folder, and it works in singleplayer but not on a server, that's really odd and I don't know the cause.  Are you using Forge as well?

**Comment by MinetopiaFan135794** [comment]
> I don't fully understand what you mean by "make a copy from the map". If you're using the "re-create world" no i copy the map in .saves

**Comment by MinetopiaFan135794** [comment]
> If you're actually copying the world folder, and it works in singleplayer but not on a server, that's really odd and I don't know the cause. Are you using Forge as well? yes but for this plugin i use 1.12.2 liteloader

**Comment by MinetopiaFan135794** [comment]
and when i upload the map from .backups to my server i come in a void world

**Comment by MinetopiaFan135794** [comment]
and when i upload the .saves file not copy to my server i come ook in a void world

**Comment by MinetopiaFan135794** [comment]
Support?

**Comment by Pokechu22** [comment]
I've been busy, sorry for not replying.

1. Does the server you are downloading from use Forge with mods?
2. Do those mods add new blocks or items?
3. Do those mods add new dimensions?
4. Does the server you are trying to use the map on have the same mods, on the same versions?

**Comment by MinetopiaFan135794** [comment]
> I've been busy, sorry for not replying.
> 
> 1. Does the server you are downloading from use Forge with mods? no
> 2. Do those mods add new blocks or items? nvt
> 3. Do those mods add new dimensions? nvt
> 4. Does the server you are trying to use the map on have the same mods, on the same versions? nvt

**Comment by MinetopiaFan135794** [comment]
it use spigot

**Comment by MinetopiaFan135794** [comment]
with plugins

**Comment by MinetopiaFan135794** [comment]
> > I've been busy, sorry for not replying. No problem i I won't insist like that anymore

**Comment by MinetopiaFan135794** [comment]
NVT = N / A

**Comment by MinetopiaFan135794** [comment]
I do the wrong coords now its work sorry

**Comment by Pokechu22** [comment]
Ah, so the spawn position in the world on the spigot server was not in an area you had downloaded, so you were getting void until you traveled to the area you had downloaded.  That makes sense.
