### ISSUE TITLE
[FEATURE] Full World

### ISSUE THREAD

**Issue by MinetopiaFan135794** [Pokechu22/WorldDownloader#196]
I don't even know if it is possible but my idea is that as an addon (like now hologram support) you can set that you can download a whole world without having to get into those chunks during the download or have ever been there at all
                                                                                

                                   
                                                                                thanks

**Comment by Pokechu22** [comment]
It's not possible.  The server only sends information for chunks you're nearby; you have to load them for them to be sent and thus saved.

If you're in a situation where you need the whole world, you do have one other option: ask a server administrator to send you a copy of it.  Otherwise, you'll need to load it yourself.

**Comment by MinetopiaFan135794** [comment]
THX
