### ISSUE TITLE
Saving gets stuck...

### ISSUE THREAD

**Issue by dillfrescott** [Pokechu22/WorldDownloader#199]
I tried to download maps and many times they get stuck saving...

**Comment by Pokechu22** [comment]
Can you clarify what you mean by "stuck saving"?  Is it stuck on the save progress screen?  If so, what step is it stuck on?

**Comment by dillfrescott** [comment]
https://i.ibb.co/wN1mDcN/image0.jpg

Right here, just spinning my view around slowly forever until I End Task the entire game closed.

**Comment by dillfrescott** [comment]
I am using the forge version, but I believe I've had it happen with the base edit version as well.

The only other thing i have is a mini map installed (with the full screen map addition) to see what chunks I've already downloaded.

**Comment by Pokechu22** [comment]
Hmm, well, that does appear to be it actually getting stuck.  Is there anything strange in the log file?  The chunk at -4, 0 contains blocks from -64, 0 to -49, 15; is there anything strange there?

There's a chance that it is a conflict with the minimap, but that doesn't seem *super* likely to me.

**Comment by dillfrescott** [comment]
https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap

This is the minimap. complete with a separate but technically full world map integration.

I'm just trying to download the main hub of play.hivemc.com (The Hive). I doubt there's anything too odd there...

**Comment by dillfrescott** [comment]
I've had it get stuck on Hypixel too.

**Comment by dillfrescott** [comment]
Main skywars lobby on Hypixel to be specific

**Comment by Pokechu22** [comment]
Can you upload a full logfile to gist.github.com and share it here?

**Comment by dillfrescott** [comment]
That's just a regular old minecraft log from the log folder right?

**Comment by dillfrescott** [comment]
Or is there a special log file made by the mod?

**Comment by Pokechu22** [comment]
Just the regular log file.

**Comment by dillfrescott** [comment]
https://gist.github.com/DillFrescott/3227acb5260804ab5f6c081b573253d3

**Comment by dillfrescott** [comment]
I hope this is the right log. I did the latest one which should be it.

**Comment by Pokechu22** [comment]
Yeah, that's the right log.

What's odd there is that it did successfully save the chunk at -4, 0 a few times (when you unloaded it naturally due to walking far away from it).  There's one block entity in it (a skull at -49, 24, 13), which shouldn't cause any problems.  So I'm not sure what it's getting stuck on.

If possible, I'd like you to get a stacktrace.  First, launch Minecraft.  Then open a command window (Windows+R, type "cmd"), and then type "jps" and press enter.  You should see something like this:

```
7576 Jps
10684 Main
```

If you instead see this:

```
'jps' is not recognized as an internal or external command,
operable program or batch file.
```

then you'll need to install OpenJDK8 from [here](https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot).

Next, run `jstack 10684` (replace `10684` with the PID from `jps`).  There should be some long output; upload that to gist.github.com.  (You can use `jstack 10684 | clip` to copy it to the clipboard automatically).  Hopefully these instructions work; I'm not entirely sure what steps need to be taken to actually install jstack.

**Comment by dillfrescott** [comment]
Ok. I'm a bit busy right now so I'll have to do that in a bit

**Comment by dillfrescott** [comment]
ok I'm back

I apologize for taking so long.

I installed OpenJDK8 (that comes with jstack btw)

i get this when I type jps in console:

C:\Users\cross>jps
6724 EntryPoint
16216 Jps

that looks a bit different than your example. is EntryPoint the equivalent of Main?

**Comment by dillfrescott** [comment]
Hmm... It doesn't seem to get stuck using OpenJDK8, but using plain old Java makes it get stuck it seems.

let me uninstall jdk8 and try with normal java again.

**Comment by Pokechu22** [comment]
Oh, right, MultiMC - yeah, `EntryPoint` should be the equivalent to `Main`.  (I'm not entirely sure what the rule for the name is, possibly it's the main class)

**Comment by dillfrescott** [comment]
Whelp it worked on regular Java 8 too now...

Could it have been something I did that fixed it or a Windows update?

**Comment by dillfrescott** [comment]
Computers are strange...

I can let you know if it does it again

**Comment by dillfrescott** [comment]
Also, one more question. Would I see more FPS in Minecraft if i used something like JDK 11? If it even boots up

**Comment by Pokechu22** [comment]
Mojang ships a specific version of Java 8 for compatibility reasons, and a lot of mods don't work right on Java 9+ (mainly for 1.12 and earlier though).  Java 11 does have some improvements, but I'm not sure how much of a difference they make on framerate (I haven't tested myself).

I don't know what might have fixed it.  I don't think a Windows update would affect things; the closest I can think of would be antivirus software messing with files.  It's more likely that this is some kind of weird timing bug that happened a few times randomly and now isn't happening due to, say, different amounts of other work going on.

Do keep OpenJDK 8 installed just in case it happens again.  I'm not sure whether you can use `jstack` from OpenJDK 8 with the normal Java 8 runtime (it's worth testing).  But I'm pretty sure that OpenJDK 8 and the regular Java 8 runtime are basically the same thing nowadays (just downloaded from different places and with a slightly different license agreement) so I wouldn't expect a bug to happen on one and not the other (for the same version at least).

**Comment by dillfrescott** [comment]
Gotcha. Thanks for the information. Java 11 works pretty much the same for vanilla, but I'd assume it would cause some modpacks to crash.

I'll do what you said in the instructions if it ever starts happening again.

Thank you for the help I really appreciate it. With half of these github projects, you are lucky to get a one word response if anything. It truly shows you stay on top of things and help us if we have issues. :)
