### ISSUE TITLE
No mod folder

### ISSUE THREAD

**Issue by TheDeathStar3** [Pokechu22/WorldDownloader#203]
I know that it is not a problem with the mod but when I look in the .minecraft folder there is no folder named "mods". But even if I add a folder called that, and put the mod inside the folder it still does not work. Please help

**Comment by Pokechu22** [comment]
Which version of Minecraft are you trying to install the mod for?  What mod loader are you using?

**Comment by TheDeathStar3** [comment]
I am tried using the base edit world downloader named "1.16.3" in both 1.16.3 and 1.16.4. I heard that the 1.16.3 world downloader is actually for 1.16.4 which is the version I am wanting to use. I also do not know if I choose the base edit, light mod wdl or the forge one. But the base edit one sounded like it was the one I need to choose.

**Comment by Pokechu22** [comment]
You want to use the 1.16.4 version on 1.16.4; although there is a chance that the 1.16.3 build would work on 1.16.4, now that there's a proper 1.16.4 build there's no reason to risk it.

The base edit version can't be installed in a mods folder; you need to insert it into the minecraft jar directly (which is a bit convoluted; you can also use MultiMC to do it).  There are details in the [forum post](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2520465-world-downloader-mod-create-backups-of-your-builds#Installation).

Still, you probably want to use the Forge version instead since it is much easier: just install Forge from [their download site](https://files.minecraftforge.net/), and *then* a `mods` folder will be created.  Forge will load the Forge version of WDL if you put it in the mods folder, without any further work.

**Comment by TheDeathStar3** [comment]
oh ok, thanks.

**Comment by TheDeathStar3** [comment]
Wait, I do not see a forge 1.16.4 version on the latest release page, where do I get it?

**Comment by Pokechu22** [comment]
GitHub seems to have been a bit misleading about the "latest release"; the newest one is [4.1.1.0](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.1.1.0) which until just now I had tagged as a pre-release.  The sidebar thus listed [4.1.0.2](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.1.0.2) as the latest release instead, which didn't support 1.16.4.  (I linked 4.1.1.0 in the forum post, as I usually do; GitHub changed the way releases are shown a few months ago and I guess that means my use of pre-release doesn't really work well anymore).

You can find WorldDownloader-forge-4.1.1.0-mc1.16.4.jar at the bottom of the list in v4.1.1.0.  Sorry for the confusion.

**Comment by TheDeathStar3** [comment]
thankyou so much.
