### ISSUE TITLE
Glitch with mods

### ISSUE THREAD

**Issue by dillfrescott** [Pokechu22/WorldDownloader#206]
I have Sodium, Lithium, and Phosphor installed (fabric) for 1.16.4

And when trying to use the baseedit world downloader it works fine except when It comes to viewing the saved world. Everything is the void.

**Comment by Pokechu22** [comment]
The base-edit builds are not designed to be used with mods.  I'm somewhat surprised that it worked at all, but if you're getting a void world, that probably means that chunks didn't save, only level.dat (which defaults to void for new chunks in the downloaded world).  There probably is a conflict either with fabric or one of the other mods, which should eventually be fixable when proper fabric builds exist (see #133).

Since none of the mods you listed add content, I recommend just using a separate install without them when downloading.  You should be able to move and use the downloaded world in the modded install afterwards.

**Comment by dillfrescott** [comment]
Ok thanks. I just thought I'd let you know as a heads up.

I'll do what you suggested and have a separate instance.
