### ISSUE TITLE
Override Gamemode to Spectator

### ISSUE THREAD

**Issue by autowert66** [Pokechu22/WorldDownloader#218]
In Options / World Overrides... / Game Mode you can change the game mode to Creative, Survival or Survival Hardcore but not to Spectator. 
It would be cool if you could add the game mode spectator to this option.
😁

**Comment by Pokechu22** [comment]
Thanks for the suggestion.  It probably doesn't exist because the relevant code predates spectator mode, but shouldn't be too hard to add.

As a work-around, cheats are enabled by default in the downloaded world, so you can use `/gamemode spectator` or `F3+N` (in some versions you may need to be in creative for the latter to work).

**Comment by Pokechu22** [comment]
This will be implemented in the next release (whenever that is).
