### ISSUE TITLE
WorldDownloader doesn't save chest contents

### ISSUE THREAD

**Issue by WolfyRed** [Pokechu22/WorldDownloader#221]
Not for chests, nor double chests, does it save the contents of them.

I'm not sure if this is a mc1.12.2 only thing, since I've only used that version, but it doesn't save chest contents.

Or if WorldDownloader doesn't like saving NBT Data from Spigot/Paper Servers...

**Comment by IceCruelStuff** [comment]
It doesn't save chest contents unless you open the chests

**Comment by Pokechu22** [comment]
You have to open chests while downloading to save their contents.  The server only sends the chest content when the chests are opened (and the same is true for most other inventories, such as furnaces and hopper minecarts).  You'll know it's been saved because a message will appear in chat (only visible to you, not to other players).

If you previously saved chest contents and then download the same world again, WDL will import the chest contents from the previous save for chests that you don't save during the second download.  (It also merges chunks from the previous download with those from the new download).

**Comment by WolfyRed** [comment]
> 
> 
> You have to open chests while downloading to save their contents. The server only sends the chest content when the chests are opened (and the same is true for most other inventories, such as furnaces and hopper minecarts). You'll know it's been saved because a message will appear in chat (only visible to you, not to other players).
> 
> If you previously saved chest contents and then download the same world again, WDL will import the chest contents from the previous save for chests that you don't save during the second download. (It also merges chunks from the previous download with those from the new download).

How do I open all of them if there's a house made of chests

**Comment by Pokechu22** [comment]
Be methodical: go through one column of chests at a time, and try to avoid missing any.

Or just don't worry about it; if you don't feel the need to go through all of the chests while on the server, then you probably won't need to go through them all in the downloaded world, right?

**Comment by WolfyRed** [comment]
I'm talking about like if someone put a chest somewhere underground in a server I want to archive (close to) correctly, is there a way to auto-open any chests in a radius?

**Comment by Pokechu22** [comment]
Ah.  Unfortunately, that isn't possible (and with how the Minecraft protocol works, wouldn't be particularly feasible to implement).  The ideal way to archive a server is to get the map from the server owner, but of course that's generally not possible, in which case you will need to skip some things (or spend a lot of time looking around for chests that are hidden all over the place).

As a side note, note that not all block entities need to be manually saved; for instance, signs are a block entity, but their contents is sent when the chunk is loaded.

**Comment by WolfyRed** [comment]
Ok then this issue has no meaning
