### ISSUE TITLE
1.9.4 Warning: Some files have invalid hashes!

### ISSUE THREAD

**Issue by capfan** [Pokechu22/WorldDownloader#25]
Receiving the following message when logging into a server:  

[WorldDownloader update check thread/INFO]: [CHAT] [WorldDL] Some files have invalid hashes!  Your installation may be corrupt or compromised.  Please use caution, and consider redownloading from the Official Minecraft Forums thread.

The warning persists when WD is the only mod installed.  I have re-downloaded, but the files are identical.

WD version: mod-litemodwdl1.9.4_gradle-1.9.4a-beta1-mc1.9.4.litemod
Liteloader version: liteloader-installer-1.9.4-00-SNAPSHOT.jar (Build #10)
Forge version: forge-1.9.4-12.17.0.1917-1.9.4

**Comment by Pokechu22** [comment]
Whoops...  I think I put the 1.9 hash information into the 1.9.4 release (which will cause this).  Hashing is part of the [update checker](https://github.com/Pokechu22/WorldDownloader/wiki/Update-checker), so I can modify the files it checks without needing to fully redo an update.  For the moment, I've just disabled hash checking for 1.9.4; after I've done a bit of testing I'll re-add it, hopefully with the correct hashes.

**Comment by Pokechu22** [comment]
OK, figured it out.  Turns out that it wasn't caused by the wrong hash info being added, but instead it was caused by a small change made in the litemod version.

Due to the fact that both the litemod and the base edit use the same update checker (something that I hope to change in the future, but haven't done yet), both use the same list for hashes.  Right now, if the two versions have different hashes for a file between them, it's represented as a list, EG

```json
{
    "Hash": ["130f1567170c863ec079ace818109b7e", "149410e17e1d9e419425c494cd52d931"],
    "RelativeTo": "wdl.WDLMessages",
    "File": "WDLMessages$MessageRegistration.class"
}
```

But I didn't consider the case where a file is present in only one version.  And, it just so happened that a [minor-seeming change in crash report handling](https://github.com/uyjulian/WorldDownloader/commit/4118006fd0100189958901b4bcb1f5e8999c0b4b#diff-16b26e727cf9eccbec8f9c54af06644eL357) means that what previously was a separate (very small) file is now just part of one bigger file.

```json
{
    "Hash": ["af9e04ad94585dde7af115eb2c3b0beb"],
    "RelativeTo": "wdl.WDLHooks",
    "File": "WDLHooks$1.class"
}
```

While the code that generated the hash there did it because the file isn't present in one version, it's actually interpreted as "there is only one valid hash".  And since that file doesn't exist, it can't be hashed, leading to the mod assuming the file is broken, thus generating the message.

I've removed the hash check for that file, so that message should no longer (incorrectly) occur.  In the future, I'll have to make a way of better handling cases where a file is present in one version but not in another.
