### ISSUE TITLE
Does WLD implement any killswitch feature?

### ISSUE THREAD

**Issue by Hink1** [Pokechu22/WorldDownloader#38]
While attempting to a server using the liteloader version of WLD (1.10a-beta1-llv1-mc1.10.2) I was kicked. I think they were using this plugin: https://www.spigotmc.org/resources/anti-worldownloader.10616/

Does WLD have a kill-switch feature?

**Comment by Pokechu22** [comment]
It has a permission system.  The goal is to make it so that people can use the mod in situations where it works well while still giving server-owners some level of control.  Kicking was not the intended use, but has become a thing (there are some tweaks I have in mind to how the packets will work to avoid kicking while still allowing permissions to be handled).  When used correctly, I'd say that it works well and shouldn't be intrusive, but some servers do not use it well.

[The reference for this plugin message-based permission system is hosted on wiki.vg](http://wiki.vg/Plugin_channels/World_downloader), and hopefully should clear things up.

**Comment by TypeV** [comment]
Can't you make the channels one-way? (Client only listens to server packets, and client doesn't send any packets)

**Comment by Pokechu22** [comment]
Theoretically, yes.  In practice, not allowing serverbound communication makes things a _lot_ harder.  For one, you can't use plugin channels (as to use plugin channels, both the server and client *must* send a `REGISTER` packet to the server), meaning you'd need to do something more complex or more ugly.  The other issue is that the serverbound packet the mod uses is there to help synchronize things (you only want to receive permissions after changing worlds once you've saved the previous world; permissions from the new world don't apply).  The popular method of using the server list ping is something that I refuse to do, simply because it's _really_ unstable (for whatever reason, the ping fails 50% of the time on my **local** test server...) and also can't be changed without disconnecting and reconnecting.  And the other option is chat messages, which I could use but would be a bit of a mess (especially since § codes are much harder in newer versions of bukkit/spigot).

The one thing I plan on changing at some point in the future is moving the REGISTER packet to when the mod is actually used, though, so that you don't have issues on first joining and instead get a notice that some servers may kick you and such (so that you can avoid issues).  That's been a little hard (the same timing issues from before) but I've been working on it.
