### ISSUE TITLE
Holographic Floating Text 

### ISSUE THREAD

**Issue by PulseSurge** [Pokechu22/WorldDownloader#4]
The floating text that's on most servers goes with the world download, is there anyway you can remove that from coming with the world you download

**Comment by Pokechu22** [comment]
I don't really know how they work, but I'll look into it.  I'm pretty sure that the base design for them is [asdjke's, found here](https://www.youtube.com/watch?v=q1B19JvX5TE). According to there, they're made up of an `EntityHorse` and a `WitherSkull`, although I'll have to use MC-Edit to verify.  It might be hard to tell the difference between a hologram and a normal named entities.

**Comment by Pokechu22** [comment]
NBTEditing points to holograms being invisible armor stands with the custom name being forced as visible.  I probably could set up a way to disable those, then.  (But I can see some people *wanting* to save them, so I might need to make a GUI).  I'll work on this some time.

**Comment by PulseSurge** [comment]
Thanks man, I'd just appreciate it if they where removed they're really not helping me at all.

**Comment by Pokechu22** [comment]
A way you could temporarily work around this is just using the `/kill` command to remove all of the armor stands.  

I think all you'd need to do is open to lan with cheats enabled (because cheats weren't enabled by default, although that will be changed with commit ff8895c) and then run the following command:

```
/kill @e[Type=ArmorStand]
```

(Hopefully I got that command right; I haven't had a chance to test it).  This will remove *all* loaded armor stands, which hopefully should only be the holograms.

I'll add a proper way to control what types of entities are saved sometime, but it might take a while.

**Comment by Pokechu22** [comment]
This is now implemented!

You can enable/disable saving entities of various types in a new GUI.  This isn't in the main release yet, but it's going to be in the next one.

The GUI currently looks like this: 
![](https://cloud.githubusercontent.com/assets/8334194/8417044/b9e3d70e-1e5e-11e5-85c5-b80e4dc038e3.png)

**Comment by Pokechu22** [comment]
[Version 1.8c](https://github.com/Pokechu22/WorldDownloader/releases/tag/1.8c) is out, with this new feature!  Enjoy!
