### ISSUE TITLE
Outdated Sources?

### ISSUE THREAD

**Issue by TypeV** [Pokechu22/WorldDownloader#42]
When I decompile MC using your csv files, add the changes and then recompile, the changed files look different than the official ones.
 EDIT: Got the sources from your minecraftforums thread, works well except for the 1.7.10, which seems to be outdated.

**Comment by Pokechu22** [comment]
My MCP mappings are a bit messy since many of them are (still) very old beta builds of MCP which I never updated.  It's a bit of a mess, unfortunately.

I'm actually working on redoing the build system so that it's based on Forge Gradle (although not Forge itself), meaning that mappings will be automatically chosen.

Here's the dates of modification for each configuration; hopefully you can find the right ones from it...

<dl>
<dt>1.7.10</dt>
<dd>9/25/14 2:58 AM</dd>
<dt>1.8</dt>
<dd>6/25/2015 7:23 PM</dd>
<dt>1.8.8</dt>
<dd>11/29/2015 4:00 PM</dd>
<dt>1.8.9</dt>
<dd>12/30/2015 3:00 PM</dd>
<dt>1.9</dt>
<dd>3/5/2016 1:42 PM</dd>
<dt>1.9.4</dt>
<dd>5/22/2016 11:40 AM</dd>
<dt>1.10</dt>
<dd>6/19/2016 11:28 AM</dd>
<dt>1.11</dt>
<dd>11/16/2016 8:37 PM</dd>
</dl>

**Comment by Pokechu22** [comment]
The new build system has been out for a while, and handles this automatically - closing the issue.
