### ISSUE TITLE
Nether Chunks 

### ISSUE THREAD

**Issue by Pencie01pd2022** [Pokechu22/WorldDownloader#49]
When I downloaded parts of the nether from a server (CosmicPVP), the single player world has chunks that are obviously out of place. Why is this happening and is there a way to fix it?
<img width="1280" alt="screen shot 2017-01-25 at 7 35 42 pm" src="https://cloud.githubusercontent.com/assets/25359146/22319201/7b33b72a-e335-11e6-9edf-cd60c8f0edc1.png">

**Comment by Pokechu22** [comment]
Those are probably newly-generated nether chunks.  While the overworld doesn't generate additional chunks in downloaded worlds (due to a custom superflat configuration that only generates air), the nether (and to a lesser extent, the end) are both free to generate new chunks (there's no good way to disable nether and end generation).  Since the seed isn't known, the wrong chunks are generated, creating the mismatch you're seeing.

This can combine with a much higher max render distance in single-player to create weird-looking chunks at the distance.

If those chunks were _right_ next to where you spawned (or places you downloaded), though, then there probably is a bug.

**Comment by Pencie01pd2022** [comment]
They're not right next to where I spawn, so it should be normal then. There is absolutely no way to stop this from happening?

**Comment by Pokechu22** [comment]
The only way to stop it from happening is to download further out, by walking further out in the nether (or to plug in the server seed in generation options, but most likely you do not have access to that).

There _might_ be a way to stop chunks in the nether and end from generating, but if there is, I haven't seen it.  I'll take another look soon.

**Comment by Pencie01pd2022** [comment]
Thanks
