### ISSUE TITLE
update all build.gradles to reflect version change in Forgegradle extensions from 0.0.4 to 0.1.0

### ISSUE THREAD

**Issue by Tsoccerguy3** [Pokechu22/WorldDownloader#64]
update build.gradle in all version folders line 27 to reflect version change in Forgegradle extensions from 0.0.4 to 0.1.0

**Comment by Pokechu22** [comment]
This doesn't work, at least not yet (from my testing).  If I set BEGradle to 0.1.0, then it forces Forgegradle 2.3 instead of 2.2, and for some reason (differences in decompile output?) using the wrong version breaks everything.  I will fix this, but it's a bit more complicated than I first thought.

**Comment by Tsoccerguy3** [comment]
I see what you mean . Gradlew setupdecompworkspace build failed after I updated . so I changed on 1.10.2 - 1.12 then it compiled .

**Comment by Tsoccerguy3** [comment]
you have all minecraft versions on the same mappings snapshot . if I compile say a 1.10.2 or a 1.11.2 against the mappings = 'snapshot_20170617' it will compile , BUT because you fixed all the name to work with the 1.12 there is no menu in 1.10.2 or 1.11.2 .

I fixed the mappings to there correct ones , but the there are naming errors on compile

Minecraft 1.10.x change mappings to stable_29
Minecraft 1.11.x change mappings to stable_32

**Comment by Pokechu22** [comment]
Everything should work with that mapping version (at least, it did when I tried it).

I'm still looking for a way to combine older stable mappings with newer snapshot mappings, so that I can use the latest names on older versions (I need the mappings to all match for compatibility, but of course newer mappings don't include older names).

If the menu doesn't appear, that probably means that base patches failed to apply, which can happen when the wrong mapping version is used, since comments can misalign things.  It might also happen if you had broken sources due to the wrong ForgeGradle version.  The fix is to set first undo any changes to the `src/base-patches` folders, and then run the `applyBasePatches` task.

**Comment by Pokechu22** [comment]
Oh yea, you may need to run `cleanCache` task to get everything to build, if you ran with the wrong version.
