### ISSUE TITLE
Crashes when connecting to hypixel

### ISSUE THREAD

**Issue by redphoinex97** [Pokechu22/WorldDownloader#65]
using 1.12

**Comment by Pokechu22** [comment]
This should have been fixed already - please update to version 4.0.0.5.  If not, please attach the crash report here.

**Comment by CodeRunner47** [comment]
Worse, WDL crashes each time after 4.0.0.5. I tried 4.0.0.6 to 4.0.1.0 and each versien crashes my minecraft.
So I have to stick to 4.0.0.5, without the ability to store Shulkerbox inventory.

B.t.w. I'm running Minecraft 1.12

**Comment by Pokechu22** [comment]
Can you post the crash report?

**Comment by CodeRunner47** [comment]
[liteloader.txt](https://github.com/Pokechu22/WorldDownloader/files/1272883/liteloader.txt)
[latest.txt](https://github.com/Pokechu22/WorldDownloader/files/1272886/latest.txt)
Hope these files can help, crash-reports folder is empty :(

**Comment by Eyremba** [comment]
As far as I know, this is an anti-worlddownloader tool of Hypixel which causes that.

**Comment by Pokechu22** [comment]
Nope, this is totally different.  Your liteloader build is out of date, which is causing mixin application issues.  Download [the installer](http://www.liteloader.com/download), point it at your instlal (if needed), and select "Upgrade liteloader".

Hypixel staff have [previously recommended the mod](https://hypixel.net/threads/guide-alexmasters-tutorial-to-a-simple-cinema-4d-render.445309/) for renders and [staff have made similar statements elsewhere](https://www.reddit.com/r/admincraft/comments/4f2unh/as_requested_i_work_at_hypixel_ama/d25u485/).

**Comment by CodeRunner47** [comment]
Dang it...... thanx for the heads up :|
I was thinking about it, but when I started downloading liteloader, it seemed like I already had the same snapshot.... Guess not, cause after updating liteloader it started to work.

Thanx, next time, although it looks like I already have the snapshot, I shall install it first before bothering all you guys. Thanx :)

**Comment by Pokechu22** [comment]
Yea, no problem - I ran into the same problem (which is why there was a release note).

I'm not entirely sure how the liteloader version numbers work, but the installer seems to have the same version even when the actual liteloader version changes.  It's confusing for sure.  In-game, there's a new version notification (though I ran into a problem where the version I used was so old that there actually wasn't a notification), but if the game crashes before you get there, that isn't much help.

Closing this issue for now (your problem's been solved, and no reply from redphoinex97).
