### ISSUE TITLE
Chests with certain items (?) corrupt save files

### ISSUE THREAD

**Issue by gourdo1** [Pokechu22/WorldDownloader#7]
I noticed that when I save certain (possibly enchanted?) items into double chests with 1.8b, the save becomes corrupt and when I try to load the single player file, Minecraft just hangs and I'm forced to use Task Manager to kill the Java service.

**Comment by Pokechu22** [comment]
Can you upload the corrupted world file?  (Or try to figure out which chest caused it and attach a screenshot?)

**Comment by gourdo1** [comment]
Having a really difficult time troubleshooting this... I suspected it was one of several non-standard items that were in a few of my chests, but when placed each in an empty chest one at a time, none of them seem to trigger the hang. However, when I open and save certain chests full of items, it's a guaranteed hang. Will find a way to upload a world file shortly, but looks like Github doesn't support anything other than images.

**Comment by gourdo1** [comment]
Ok, making some progress... It's not the items or chests themselves. It seems to be a problem with saves across multiple sessions, as that's when I get a hang. I'll see if I can drill down a bit further.

**Comment by gourdo1** [comment]
Ok, now we're cooking. Here's how I can reproduce:

1. Start on multiplayer server; Create new WDL save session (choose all default settings).
2. Save progress & log out of multiplayer server.
3. Log into single player version of world just saved. Result: WORKS FINE.

4. Start on same multiplayer server again; Re-start downloading into previously saved world.
5. Save progress & log out of multiplayer server.
6. Log into single player version of world just saved. Result: WORKS FINE.

7. Start on same multiplayer server again; Re-start downloading into previously saved world.
8. Open and close an empty double chest.
9. Save progress & log out of multiplayer server.
10. Log into single player version of world just saved. Result: MINECRAFT HANGS INDEFINITELY ON LOADING SCREEN.

**Comment by gourdo1** [comment]
Link to zip:
http://gordo.minidns.net:100/data/Minetime_com_2015-07-02_10-52-24.zip

**Comment by Pokechu22** [comment]
Reproduced with your method.  However, your download link doesn't work :/  (But since I've reproduced it, it shouldn't be too much of an issue).

Here's a [threaddump](http://pastebin.com/k6q9ugY5), for my own use (created with `jvisualvm`, which is included in the JDK): 

And it seems like there's a crash report in the output (but the game didn't stop?)  [Here's that report](http://pastebin.com/jXDp55VG)

Check and see if you have a crash report that's labeled as server that looks similar to this.

**Comment by Pokechu22** [comment]
MCEdit shows that only one chest has a tileentity.  I bet that's related.

![mcedit_chest](https://cloud.githubusercontent.com/assets/8334194/8486193/d6b5402e-20b7-11e5-8dd5-ad3c7b17b906.png)

Also, one thing to note: The chests  have to already be there before the first step -- you can't place them just before opening them.

**Comment by Pokechu22** [comment]
This only happens with one side of the chest, oddly.  I'm going to make a guess that #8 is this same bug except that the chest had been previously loaded before and thus has saved contents.  Investigating...

**Comment by gourdo1** [comment]
Sorry, don't know how else to host a zip file for free.

In any case, here's my latest crash dump:
http://pastebin.com/WR5iMv1E

**Comment by Pokechu22** [comment]
... further testing shows that this didn't actually fix it.  But I noticed something: it seems to only crash if you open a chest on the south side (if it's facing east or west); opening it on the north side doesn't cause any issues.  Reopening both of these issues (even though #8 can't be reproduced by me, I'm guessing that it isn't fixed).

I did fix one of the bugs related to this though (which may be the one leading to #8 -- it was saving the data at the wrong location).  I'm guessing that the cause of this bug is in the same code.

**Comment by Pokechu22** [comment]
I'm 99.99% sure I fixed this one, given that I no longer experience it with either side of the chest.  I'll release a beta version so that you can mess around with it, though.  If it still occurs, feel free to reopen the issue.

**Comment by Pokechu22** [comment]
[Here](https://github.com/Pokechu22/WorldDownloader/releases/tag/1.8c-beta1) is the beta release.

**Comment by gourdo1** [comment]
Looks like you made great progress. I downloaded 1.8c beta1, but unfortunately the server i always use is down tonight. Will try again to verify tomorrow...

**Comment by gourdo1** [comment]
Both issues seem to be resolved. Can't get it to crash on load anymore and don't see any half filled chests. Great job!
