### ISSUE TITLE
[1.10.2] Crashes on load with forge

### ISSUE THREAD

**Issue by alothmanmoe** [Pokechu22/WorldDownloader#71]
So i downloaded forge with liteloader and world downloader, tried running, but it kept crashing, and it was just forge, liteloader and wdl, nothing else
crash:
https://paste.ee/p/bQGB4
latest version for 1.10.2, (Version 4.0.1.7, 4.0.1.6 too)
Edit:
note with Version 4.0.1.5 it works perfectly fine

**Comment by Pokechu22** [comment]
> Caused by: java.lang.Throwable: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.LiteModWDL.json requires mixin subsystem version 0.6.8

Make sure you're running the latest liteloader build (redownload it and reinstall it, even if the version number of the installer seems to be the same).  I'll check to make sure I didn't mess up the mixin configuration on my side (I recently went in and specified minimum versions so that if an outdated mixin version was used, the game would report an error rather than appearing to work and then randomly failing later &mdash; but I entered the numbers manually, so there's a chance I got it wrong).

**Comment by alothmanmoe** [comment]
Yeah its my 3rd time installing it and got the same error over and over, didnt think i was doing anything wrong so i made this issue

**Comment by Pokechu22** [comment]
```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- deobf.com.mumfrey:liteloader:1.10.2
+--- deobf.org.spongepowered:mixin:0.6.8-SNAPSHOT
+--- deobf.com.google.guava:guava:17.0
+--- deobf.com.google.code.gson:gson:2.2.4
\--- deobf.commons-io:commons-io:2.4
```

In my development environment liteloader uses Mixin 0.6.8, but the liteloader build you're using uses 0.5.17.  And I checked my copy, and it's also 0.5.17.  That's odd...

**Comment by Pokechu22** [comment]
OK, yeah, the release liteloader is using an older version than the one I target... that's problematic.  I'll ask mumfrey what's up with that.  (**Edit**: I've also added a warning on the download page that this build has issues)

This will probably be an issue that I'll just hotfix, since I think that it will require only config changes.

**Comment by alothmanmoe** [comment]
All right thanks :D

**Comment by Pokechu22** [comment]
Alright, I've created a liteloader report: http://develop.liteloader.com/liteloader/LiteLoader/issues/41

**Comment by Pokechu22** [comment]
No response from the liteloader team.  I'll release a hotfixed version with 0.5.17 now, give me a few minutes...

**Comment by Pokechu22** [comment]
I've added a fixed 1.10.2 version to [the 4.0.1.7 release page](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.1.7).

**Comment by alothmanmoe** [comment]
all right thanks :D

**Comment by Pokechu22** [comment]
Closing for now since this should be fixed; if you encounter any issues feel free to reopen it.
