### ISSUE TITLE
New Optifine 1.12.2 U D1 pre conflict with WDL's dowload menu

### ISSUE THREAD

**Issue by Tsoccerguy3** [Pokechu22/WorldDownloader#79]
When you click on download you begin to spin and the background is not rendered . This is a conflict with Optifine 1.12.2 U D1 pre 

Liteloader version

Edit : issue not present in Optifine 1.12.2 U C9

**Comment by Pokechu22** [comment]
Confirmed, and also confirmed that it _only_ happens with the preview build.  As such, this could be an optifine bug, though it's also possible that some of my recent changes with that gui to fix several crashes and other bugs are the cause of the issue.

**Comment by Pokechu22** [comment]
Looking at [the changelog](https://optifine.net/changelog?f=preview_OptiFine_1.12.2_HD_U_D1_pre.jar):

>  - optimized visibility cullung

is probably responsible (the new "Render Regions" might also be related, but doesn't seem to be at fault since this happens either way).

------

EDIT: Also, _not_ caused by the changes in 4.0.2.0, as this also happens with 4.0.1.7.  So this is definitely optifine's fault; I just need to figure out what they're breaking now (which is going to be a hassle because optifine isn't open-source).

**Comment by Tsoccerguy3** [comment]
Opened issue on Optifine issue tracker
https://github.com/sp614x/optifine/issues/1286

**Comment by Tsoccerguy3** [comment]
From Mumfrey

Mixin has the ability to export the classes it modifies (it will also decompile them on-the-fly if fernflower is available on the classpath), so I recommend starting with that to see if you can spot any weird interactions with WDL and OF that are a result of the code getting mangled on injection.

**Comment by Tsoccerguy3** [comment]
fixed by sp614x ( closed )
