### ISSUE TITLE
Latest compile July 18 , crashes client on stop download

### ISSUE THREAD

**Issue by Tsoccerguy3** [Pokechu22/WorldDownloader#84]
Pick up latest crash log here http://sdrv.ms/TPcx5v on my OneDrive in the Pokechu22 directory

Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type class java.lang.Enum; not a subtype of implementation type interface net.minecraft.util.IStringSerializable

**Comment by Pokechu22** [comment]
This is caused by a compiler bug: https://bugs.openjdk.java.net/browse/JDK-8058112 (which is supposed to be fixed, but still seems to be happening until Java 9, and we can't use Java 9 for other reasons).  I've fixed it already (e902f9dfed1e7ce87d7b48a938588f7a69e616cd), just hadn't been pushed yet.  Try the latest build.

Note that a TON of other stuff is also super unstable right now -- I'm trying to work on 1.13 based off of the changes I know have happened, and a lot of things are in a strange state.
