### ISSUE TITLE
WDL LiteLoader doesn't seem to send WDL|Init

### ISSUE THREAD

**Issue by DoNotSpamPls** [Pokechu22/WorldDownloader#99]
Hello,
I am currently adding functionality to my plugin to block WDL (I know the companion plugin exists, but it's been requested by a lot of people). The problem is that, the mod doesn't seem to be sending anything on WDL|INIT for some reason. I'm using WDL LiteLoader version 4.0.3.1 on Minecraft 1.12.2 and a Paper 1.12.2 server running the latest version. When I listen for the channels, I only get `MC|Brand` and an empty channel name.

Here is what I get as debug in the game: ![](https://ranked.is-la.me/7fb4f7.png)

And here is what I have as code:
```java
public void onEnable() {
  getServer().getMessenger().registerIncomingPluginChannel(this, "WDL|INIT", new PacketMessageListener(this););
  getServer().getMessenger().registerOutgoingPluginChannel(this, "WDL|CONTROL");
}
```

```java
public void onPluginMessageReceived(String channel, Player player, byte[] value) {
  if ((channel.equalsIgnoreCase("WDL|INIT")) || (channel.contains("WDL")) {
    player.sendMessage("You have the WDL mod! (debug)");
   }
}
```

I'm genuinely lost on what could cause this, and I wonder if you could help me out. Thank you very much.

**Comment by Pokechu22** [comment]
Hmm, this is weird.  It should be sending it for sure.  I did mess with when the channels were sent because the channel names were forced to change for 1.13, but it should still be sending everything, just at a different time.  I'll investigate.

Anyways, standard disclaimer about use of these channels: _please_ don't use them for evil; use the control packets and don't kick players as kicking players leads to a really confusing user experience (getting kicked before the rules are even shown).

**Comment by DoNotSpamPls** [comment]
The old version of the plugin (not made by me) kicked the players, which is something I really don't like as well, so I will be implementing the control packets, although I probably won't be implementing the request functionality - from what I've seen the users of my plugin are people who don't want **anyone** touching their worlds, so it wouldn't make much sense. If someone wants that feature I'll recommend them the companion plugin, since it has more fine-grained control anyway.

**Comment by Tsoccerguy3** [comment]
I would recommend using the existing WDL server side plugin . Instead of kicking , warning and banning , just set the server permissions . The best way to protect content against commercial gain on a authors work is to publish on a site like PMC . 

Here is an example of Extreme abuse server side . https://www.planetminecraft.com/project/rowlings-realm/ . This map is not even made by the owner , but logging in will result in permanent BAN . Then you must apply to be UN-banned and make a donation.

https://www.planetminecraft.com/project/harry-potter-adventure-map-3347878/ , here is a free map on PMC , that is donation funded development , with full copyright protection.

A lot of the published content on PMC is far superior to content I've seen on servers that have implemented a WDL Banning plugin . MIT Licenced

**Comment by DoNotSpamPls** [comment]
Uhh, I'm not sure how that is related, but I don't want any more dependency plugins to install, people are already dumb enough to not install ProtocolLib, which is the only dependency. Of course, allowing owners to ban is not good, so I'm not going to be allowing that. I will only allow to disable WDL, with no other effects.

**Comment by Pokechu22** [comment]
I can confirm that this is a bug on my end, unfortunately; it seems to be caused by both liteloader and WDL reading the same packet and WDL not getting all the data it needs as a result.  I'll push out a new build as soon as I can (but I also want to get 1.13.1 ready at the same time) with this and several other bugfixes, and deprecate the current builds at the same time (since it's only the litemod, it's pretty easy to update anyways).  Sorry about this; I was worried that this would happen and it seems my testing didn't catch it.

**Comment by DoNotSpamPls** [comment]
Thank you very much for the quick response! I'm eagerly awaiting the fix :stuck_out_tongue:

**Comment by Pokechu22** [comment]
I've fixed this, see the linked commit for more information (it ended up being rather complicated, though I think the fix is relatively clean with all of the information given).  Github's being slow right now, though, so it might take a while to show up.
